[package]
name = "japesinator/Idris-Profunctors"
version = "0.1.0"
authors = []

[targets.lib]
path = "src"
name = "profunctors"
mods = [ "Data.Profunctor"
       , "Data.Profunctor.Cayley"
       , "Data.Profunctor.Closed"
       , "Data.Profunctor.Codensity"
       , "Data.Profunctor.Composition"
       , "Data.Profunctor.Fold"
       , "Data.Profunctor.Iso"
       , "Data.Profunctor.Index"
       , "Data.Profunctor.Lens"
       , "Data.Profunctor.Lens.At"
       , "Data.Profunctor.Prism"
       , "Data.Profunctor.Trace"
       , "Data.Profunctor.Traversal"
       , "Data.Verified.Profunctor"
       ]
idris_opts = ["-p", "contrib"]
